fix: disable unload metrics
Chromium introduced unload metrics in:
https://chromium-review.googlesource.com/c/chromium/src/+/2314877

Which would cause some DCHECKs to assert in Electron:
https://github.com/electron/electron/issues/27717

And it would then crash and make some tests fail:
crashReporter module should send minidump when sandboxed renderer crashes api-crash-reporter-spec.ts 643 ms
Error message:
ptype: expected 'browser' to equal 'renderer'
Error stack trace:
AssertionError: ptype: expected 'browser' to equal 'renderer'
    at checkCrash (electron\spec\api-crash-reporter-spec.ts:39:35)
    at Context.<anonymous> (electron\spec\api-crash-reporter-spec.ts:154:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

This patch temporarily disables the metrics so we can have green CI, and we
should continue seeking for a real fix.

Patch-Dir: src/electron/patches/chromium
Patch-Filename: disable_unload_metrics.patch